before:
  hooks:
    - go test ./...

builds:
  -
    env:
      - CGO_ENABLED=0
    ldflags:
      - '-s -w -X "github.com/nslhb/terraform-k8s/version.Version={{ .Version }}" -X "github.com/nslhb/terraform-k8s/version.Prerelease="'
    goos:
      - linux
      - windows
      - darwin
    targets:
      - amd64
      - arm64

archives:
  -
    format: zip
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: false
    files: # Avoid packaging any extra (default) files
      - none*

checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256

changelog:
  skip: true