// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	tfe "github.com/hashicorp/go-tfe"
	mock "github.com/stretchr/testify/mock"
)

// Variables is an autogenerated mock type for the Variables type
type Variables struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, workspaceID, options
func (_m *Variables) Create(ctx context.Context, workspaceID string, options tfe.VariableCreateOptions) (*tfe.Variable, error) {
	ret := _m.Called(ctx, workspaceID, options)

	var r0 *tfe.Variable
	if rf, ok := ret.Get(0).(func(context.Context, string, tfe.VariableCreateOptions) *tfe.Variable); ok {
		r0 = rf(ctx, workspaceID, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tfe.Variable)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, tfe.VariableCreateOptions) error); ok {
		r1 = rf(ctx, workspaceID, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, workspaceID, variableID
func (_m *Variables) Delete(ctx context.Context, workspaceID string, variableID string) error {
	ret := _m.Called(ctx, workspaceID, variableID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, workspaceID, variableID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, workspaceID, options
func (_m *Variables) List(ctx context.Context, workspaceID string, options tfe.VariableListOptions) (*tfe.VariableList, error) {
	ret := _m.Called(ctx, workspaceID, options)

	var r0 *tfe.VariableList
	if rf, ok := ret.Get(0).(func(context.Context, string, tfe.VariableListOptions) *tfe.VariableList); ok {
		r0 = rf(ctx, workspaceID, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tfe.VariableList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, tfe.VariableListOptions) error); ok {
		r1 = rf(ctx, workspaceID, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Read provides a mock function with given fields: ctx, workspaceID, variableID
func (_m *Variables) Read(ctx context.Context, workspaceID string, variableID string) (*tfe.Variable, error) {
	ret := _m.Called(ctx, workspaceID, variableID)

	var r0 *tfe.Variable
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *tfe.Variable); ok {
		r0 = rf(ctx, workspaceID, variableID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tfe.Variable)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, workspaceID, variableID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, workspaceID, variableID, options
func (_m *Variables) Update(ctx context.Context, workspaceID string, variableID string, options tfe.VariableUpdateOptions) (*tfe.Variable, error) {
	ret := _m.Called(ctx, workspaceID, variableID, options)

	var r0 *tfe.Variable
	if rf, ok := ret.Get(0).(func(context.Context, string, string, tfe.VariableUpdateOptions) *tfe.Variable); ok {
		r0 = rf(ctx, workspaceID, variableID, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tfe.Variable)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, tfe.VariableUpdateOptions) error); ok {
		r1 = rf(ctx, workspaceID, variableID, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
