apiVersion: v1
kind: ConfigMap
metadata:
  name: say-hello
data:
  to: world
---
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: hello
spec:
  organization: hashicorp-team-demo
  secretsMountPath: "/tmp/secrets"
  module:
    source: "joatmon08/hello/random"
    version: "4.0.0"
  outputs:
    - key: my_pets
      moduleOutputName: list_of_pets
  variables:
    - key: hello
      value: rosemary
      sensitive: false
      environmentVariable: false
    - key: second_hello
      valueFrom:
        configMapKeyRef:
          name: say-hello
          key: to
      sensitive: false
      environmentVariable: false
    - key: secret_key
      sensitive: true
      environmentVariable: false
    - key: AWS_SECRET_ACCESS_KEY
      sensitive: true
      environmentVariable: true
    - key: CONFIRM_DESTROY
      value: "1"
      sensitive: false
      environmentVariable: true
  additionalProviders:
  - name: "confluentcloud"
    source: "https://github.com/parkside-securities/terraform-provider-confluentcloud/releases/download/v.0.0.2/terraform-provider-confluentcloud-v0.0.2-linux-amd64.tar.gz"
  - name: "kafka"
    source: "https://github.com/Mongey/terraform-provider-kafka/releases/download/v0.2.4/terraform-provider-kafka_0.2.4_linux_amd64.tar.gz?checksum=file:https://github.com/Mongey/terraform-provider-kafka/releases/download/v0.2.4/checksums.txt"