# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/app.terraform.io_workspaces.yaml
# +kubebuilder:scaffold:crdkustomizeresource

configurations:
- kustomizeconfig.yaml
